### ISSUE TITLE
What's with the obvious malware script?

### ISSUE THREAD

**Issue by lietu** [Troplo/office-install.sh#6] opened 2024-05-25 21:20 UTC
https://github.com/Troplo/office-install.sh/blob/795dca88d45835fa4d7c186f0fcc189580ceeb1a/office-install.sh#L36

This is not how you install Wine on Arch.

https://github.com/Troplo/office-install.sh/blob/795dca88d45835fa4d7c186f0fcc189580ceeb1a/office-install.sh#L80

Another random binary blob download from a shady server.

https://github.com/Troplo/office-install.sh/blob/795dca88d45835fa4d7c186f0fcc189580ceeb1a/office-install.sh#L167

And more.

https://github.com/Troplo/office-install.sh/blob/795dca88d45835fa4d7c186f0fcc189580ceeb1a/office-install.sh#L184

And it just keeps going.

This is not how you do legitimate tooling. This is how you distribute malware. If you're distributing legitimate Microsoft files, you're also likely breaking their license terms.

**Comment by SteavenGamerYT** [comment] 2024-05-26 00:23
ops i have installed it

**Comment by KweezyCode** [comment] 2024-05-26 08:10
duplicate of https://github.com/Troplo/office-install.sh/issues/4

**Comment by Troplo** [comment] 2024-05-26 08:38
While you both are of course correct and completely justified about the shadiness of it downloading seemingly random archives, I made the script to simply install Office on my computers since the official Office installer doesn't work correctly in WINE, and didn't really plan for many other people to use it.

> https://github.com/Troplo/office-install.sh/blob/795dca88d45835fa4d7c186f0fcc189580ceeb1a/office-install.sh#L36
> 
> This is not how you install Wine on Arch.
It doesn't install Wine on Arch using `pacman` or the likes, it downloads and installs an old version of Wine to a local directory as you can see. Of course this could have been downloaded directly from an Arch mirror, and I'm not sure why I didn't do that, you can check the sha256sum for the original Wine 9.7, and my copy, and it will be identical as I made no changes to it.
> 
> https://github.com/Troplo/office-install.sh/blob/795dca88d45835fa4d7c186f0fcc189580ceeb1a/office-install.sh#L80
> 
> Another random binary blob download from a shady server.
> 
> https://github.com/Troplo/office-install.sh/blob/795dca88d45835fa4d7c186f0fcc189580ceeb1a/office-install.sh#L167
> 
> And more.
> 
> https://github.com/Troplo/office-install.sh/blob/795dca88d45835fa4d7c186f0fcc189580ceeb1a/office-install.sh#L184
> 
> And it just keeps going.
> 
> This is not how you do legitimate tooling. This is how you distribute malware. If you're distributing legitimate Microsoft files, you're also likely breaking their license terms.
This wasn't advertised as a script that legitimately installs Office using the janky Microsoft Office installer, it's a simple script that installs Office by downloading a preconfigured WINEPREFIX. Of course me saying there's no malware doesn't mean anything, and that's fair enough on your part, it does appear as a sketchy malware script, however, I just thought it was convenient for it to simply download a WINEPREFIX that's already setup with a working install of Office.

**Comment by Troplo** [comment] 2024-05-26 08:53
But yes you also make a fair point regarding the Microsoft software re-distribution, and documentation to install it is needed for sure rather than a script that downloads stuff not directly from Microsoft. Although truthfully, the script really doesn't do much of anything special, there's no custom patches or anything to either Wine or the Office binaries, it's really just the installation that's the main hurdle, which I wanted to solve with this script.

**Comment by Troplo** [comment] 2024-05-26 14:50
I have removed the script as if it looks like a front for malware distribution then I definitely don't want to be associated with it even if I know this isn't the case. I will however in the future provide actual steps to replicate such an install locally as mentioned earlier.

I hope these responses clear up any misconceptions and if you have any other concerns please let me know.

**Closed** 2024-06-04 23:05 UTC

**Comment by KweezyCode** [comment] 2024-07-14 19:23
> I will however in the future provide actual steps to replicate such an install locally as mentioned earlier.

any news?

**Comment by SteavenGamerYT** [comment] 2024-07-14 21:08
> any news?

i dont think so

**Comment by MattiaPARRINELLO** [comment] 2025-05-16 07:02
Hello, is there any update??

**Comment by sihawken** [comment] 2025-11-15 17:00
> I have removed the script as if it looks like a front for malware distribution then I definitely don't want to be associated with it even if I know this isn't the case. I will however in the future provide actual steps to replicate such an install locally as mentioned earlier.
> 
> I hope these responses clear up any misconceptions and if you have any other concerns please let me know.

I fully believe that there is no malware and that the prefix/wine download was more out of convenience, but I can't find any documentation to replicate your steps. I am looking to do this on my own.

I saw that you mentioned that office doesn't normally install in wine, do you mind explaining your steps so we can recreate this on our own? Perhaps make scripts that automate the process?

Does it require installing office first in windows and coping over the required files/registry entries etc? Do you mind providing these details?
